ApiFinal/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ApiFinal.Models
{
    [Table("Productos")]
    public class Producto
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]

        [Column("IdProducto")]
        public int IdProducto { get; set; }

        [Column("Nombre")]
        public string Nombre { get; set; }

        [Column("Precio")]
        public double Precio { get; set; }

        [Column("Imagen")]
        public string Imagen { get; set; }

    }
}

ApiFinal/Models/Productos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> Precio { get; set; }
        public string Imagen { get; set; }
    }
}

ApiFinal/Controllers/ProductoController.cs
using ApiFinal.Models;
using ApiFinal.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApiFinal.Controllers
{
    public class ProductoController : Controller
    {
        RepositoryProducto repo; //referencia del clase repositoryproducto
        public ProductoController()
        {
            repo = new RepositoryProducto();
        }

        //Nos va a permitir mostrar los productos
        public ActionResult ListaProductos(int? id)
        {
            if (id != null)
            {
                List<int> codigosProductos;
                if (Session["PRODUCTOS"] == null)
                {
                    codigosProductos = new List<int>();
                }
                else
                {
                    codigosProductos = Session["PRODUCTOS"] as List<int>;
                }
                codigosProductos.Add(id.Value);
                Session["PRODUCTOS"] = codigosProductos;
                ViewBag.Mensaje = "Productos en Carrito: " + codigosProductos.Count();
            }
            ViewBag.Carrito = Session["PRODUCTOS"];
            List<Producto> prod = this.repo.GetProductos();
            return View(prod);
        }
        //nos permite ver los productos que tenemos en el carrito
        public ActionResult ProductosCarrito(int? id)
        {
            if (id != null)
            {
                List<int> lista = (List<int>)Session["PRODUCTOS"];
                lista.Remove(id.GetValueOrDefault());
                if (lista.Count() == 0)
                {
                    Session["PRODUCTOS"] = null;
                }
                else
                {
                    Session["PRODUCTOS"] = lista;
                }
            }
            if (Session["PRODUCTOS"] == null)
            {
                return View();
            }
            else
            {
                List<int> lista = (List<int>)Session["PRODUCTOS"];
                List<Producto> prod = this.repo.BuscarProductos(lista);
                return View(prod);
            }
        }
    }
}

ApiFinal/Views/Producto/ListaProductos.cshtml
@using ApiFinal.Models
@{
    ViewBag.Title = "ListaProductos";
}

<h2>ListaProductos</h2>
@Html.ActionLink("Ver carrito de compra", "ProductosCarrito", "Producto")
<br />
<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>NOMBRE</th>
        <th>PRECIO</th>
        <th>IMAGEN</th>
        <th>AGREGAR AL CARRITO</th>
    </tr>
    @foreach (Producto prod in Model)
    {
        <tr>
            <td>@prod.IdProducto</td>

            <td>@prod.Nombre</td>
            <td>@prod.Precio</td>
            <td><img style="width:70px; height:70px" src="~/img/@prod.Imagen" /></td>

            @if (ViewBag.Carrito != null && ViewBag.Carrito.Contains(prod.IdProducto))
            {
                <th><img style="width:20px;height:20px" src="https://image.flaticon.com/icons/png/512/107/107831.png" /><span>Añadido al carrito</span></th>
            }
            else
            {
                <td>@Html.ActionLink("Añadir al carrito", "ListaProductos", "Producto", new { id = prod.IdProducto }, new { @class = "btn btn-primary" })</td>
            }


        </tr>
    }
</table>

ApiFinal/Views/Producto/ProductosCarrito.cshtml
@using ApiFinal.Models
@{
    ViewBag.Title = "ProductosCarrito";
}

<h2>ProductosCarrito</h2>

@if (Session["PRODUCTOS"] == null)
{

    <h2 style="color:red">
        No hay ningún producto en el carrito
    </h2>
}
else
{
    <dl class="row">
        @foreach (Producto prod in Model)
        {
            <dt><img style="width:70px;height:70px;" src="~/img/@prod.Imagen" /></dt>
            <dd>@prod.Nombre</dd>
            <dd>@prod.Precio</dd>
            <dd>
                @Html.ActionLink("Eliminar del Carrito", "ProductosCarrito", "Producto", new { id = prod.IdProducto } , null)
            </dd

            <br />
        }
    </dl>
}
@Html.ActionLink("Volver a los productos", "ListaProductos", "Producto", new { @class = "btn btn-primary" })